project_id = "fqjbzcyuswepwpvoyabn"

[functions.geocode-city]
verify_jwt = false

[functions.search-city]
verify_jwt = false

[functions.estimate-trip]
verify_jwt = false

[functions.monthly-report]
[functions.monthly-report]
verify_jwt = false

[functions.admin-list-users]
verify_jwt = false
